### PR TITLE
React rdx components

### PR DESCRIPTION
**Pull request by MarcoDDM**
**Description**
This pull request adds Redux integration to the project and introduces a new reusable Book component. It also includes the implementation of dispatching actions, adding books to the store, and removing books from the store.

**Changes Made**
- Wrapped the <App> component with the <Provider> component from react-redux.
- Passed the configured store into the <Provider>.
- Created an initialState variable for the booksSlice, containing a predefined list of books.
- Added a new reusable Book component to display books received from the slice.
- Implemented the dispatch functionality using useDispatch hook.
- Added a <Button> component with an event handler to add a book to the books array (with attributes id, title, and author).
- Added a <Button> component with an event handler to remove a book from the books array by its id.

**Checklist**
- Wrapped <App> with <Provider> and passed the store.
- Created an initialState variable with a predefined list of books.
- Added a reusable Book component to display books.
- Implemented dispatch functionality using useDispatch.
- Added a button to add a book with an event handler.
- Added a button to remove a book by its ID with an event handler.

Thanks for your review. Don't hesitate to tag me if there are any changes needed.

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @MarcoDDM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 

- You have added an initialState to the booksSlice that contains an array of books with item_id, title, author and category properties. ✅
- You have defined two reducers in the booksSlice: addBook and removeBook, that use the spread operator and the filter method to update the state immutably. ✅
- You have exported the booksSlice actions and reducer for use in other parts of the app. ✅
- You have used the useSelector hook to access the books from the state in the BookList component. ✅
- You have used the useDispatch hook to dispatch the addBook action in the NewBookForm component respectively. ✅
- You have used useState hooks to store the title and author of the new book in the NewBookForm component and updated them with onChange handlers. ✅
- You have used a button element with an onClick handler to trigger the handleSubmit function in the NewBookForm component. ✅
- You have used a button element with an onClick handler to trigger the removeBook action in the Book component. ✅

## Required Changes ♻️
_Check the comments under the review._

(Note: I am not using the GitHub inline comment feature to make this comment because I cannot highlight any code in the Files Changed section on the pull request. This is because no changes have been made to the index.js file in this pull request. Therefore, I am writing this comment as a general comment on the pull request.)

Hi, thank you for your submission. I noticed that your code in `index.js` does not meet the project requirements of using Redux with React. Here are some suggestions to improve your code:
image

- Import the Provider component from react-redux at the top of your file: `import { Provider } from "react-redux"`
- Import the store from the redux folder at the top of your file: `import store from "./redux/store"`
- Wrap the App component with the Provider component and pass the store as a prop: `<Provider store={store}><App /></Provider>`

These changes will allow you to use the useSelector and useDispatch hooks from react-redux in your App component and its children. These hooks let you access the state and dispatch actions from the Redux store without using connect or mapStateToProps/mapDispatchToProps.

I hope this helps. Please let me know if you have any questions or need further assistance.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- - [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
image

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — COMMENTED** [review]
@MarcoDDM, please ignore my comment about 
Using the ReactDOM.render method instead of the ReactDOM.createRoot method to render your app to the DOM: ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById("root"))

**Comment by MarcoDDM** [comment]
> @MarcoDDM, please ignore my comment about Using the ReactDOM.render method instead of the ReactDOM.createRoot method to render your app to the DOM: ReactDOM.render(, document.getElementById("root"))

But I already changed it... what should I do now?

**Review by addod19 — APPROVED** [review]
### Hi @MarcoDDM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job making the recommended changes as required :rocket: 
Screenshot from 2023-06-12 19-29-46



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> > @MarcoDDM, please ignore my comment about Using the ReactDOM.render method instead of the ReactDOM.createRoot method to render your app to the DOM: ReactDOM.render(, document.getElementById("root"))
> 
> But I already changed it... what should I do now?

You can leave if as so if it works

**Pull request merged**
